version:  '3.7'
services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
    - './frontend/public/:/app' # access to index.html
    - './backend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro' # access to nginx docker config
    ports:
    - ${NGINX_PORT}:4000
    depends_on:
      - php
      - frontend
  php:
    build:
      context: .
      dockerfile: ./backend/php/Dockerfile
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - mysql
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./frontend:/app
#    links:
#      - backend
    command: npm run start

