version:  '3.7'
services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
    - './server/app/public/:/usr/src/app'
    - './server/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
    - `${NGINX_PORT}:40`
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: server/docker/php/Dockerfile
    restart: on-failure
    env_file:
    - .env
    user: ${LOCAL_USER}
  client:
    build: ./client
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./frontend/src:/srv/app/feedbacks-dashboard/src
      - ./frontend/public:/srv/app/feedbacks-dashboard/public
    links:
      - server
    command: npm run start

